---
- name: Deploy Docker container with static IP
  hosts: all
  become: true
  tasks:

    - name: Create a custom Docker network
      docker_network:
        name: custom_host_network
        driver: bridge
        ipam_options:
          subnet: "192.168.1.0/24"
          gateway: "192.168.1.1"

    - name: Deploy a Docker container with static IP
      docker_container:
        name: tmp-01
        image: debian:latest
        hostname: tmp-01
        networks:
          - name: custom_host_network
            ipv4_address: "192.168.1.160"
        state: started
        restart_policy: always
        detach: true

...
