---
- name: Install K3s on Debian 12.5
  hosts: all
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: true

    - name: Install required dependencies
      apt:
        name: 
          - curl
          - apt-transport-https
        state: present

    - name: Download and install K3s
      shell: |
        curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--disable traefik" sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Ensure K3s service is started
      systemd:
        name: k3s
        state: started
        enabled: true

    - name: Verify K3s installation
      command: k3s kubectl get nodes
      register: result
      retries: 5
      delay: 10
      until: result.rc == 0

    - name: Display K3s node information
      debug:
        msg: "{{ result.stdout_lines }}"
...
  handlers:
    - name: Restart K3s
      systemd:
        name: k3s
        state: restarted
