---
# Prepare your invetory host file as follows:
#
# [oracle8]
# server1.example.com
# server2.example.com
#
# [oracle8:vars]
# ansible_user=your_ansible_user
# ansible_become=yes
# domain_name=example.com
# domain_admin_user=your_domain_admin
# domain_admin_password=your_domain_password
#
- name: Join Oracle Linux 8 servers to Active Directory domain
  hosts: oracle8
  become: yes
  vars:
    domain_name: "{{ domain_name }}"
    domain_admin_user: "{{ domain_admin_user }}"
    domain_admin_password: "{{ domain_admin_password }}"
  tasks:
    - name: Install required packages
      yum:
        name:
          - realmd
          - oddjob
          - oddjob-mkhomedir
          - sssd
          - adcli
          - samba-common
          - samba-common-tools
          - krb5-workstation
        state: present

    - name: Discover Active Directory domain
      command: realm discover {{ domain_name }}
      register: realm_discover
      changed_when: "'No such realm found' not in realm_discover.stderr"

    - name: Join the domain
      command: >
        realm join --user={{ domain_admin_user }}
        {{ domain_name }}
      args:
        stdin: "{{ domain_admin_password }}"
      register: join_domain
      changed_when: "'successfully enrolled' in join_domain.stdout"

    - name: Configure SSSD to start on boot
      systemd:
        name: sssd
        enabled: yes
        state: started

    - name: Allow domain users to log in
      lineinfile:
        path: /etc/sssd/sssd.conf
        regexp: '^access_provider =.*'
        line: 'access_provider = simple'
        insertafter: '[domain/{{ domain_name }}]'

    - name: Restart SSSD
      systemd:
        name: sssd
        state: restarted

    - name: Update PAM configuration to create home directories on login
      lineinfile:
        path: /etc/pam.d/sshd
        regexp: '^#.*pam_mkhomedir.so'
        line: 'session required pam_mkhomedir.so skel=/etc/skel/ umask=0077'
        insertafter: 'session    required     pam_limits.so'

    - name: Allow domain users to use sudo
      lineinfile:
        path: /etc/sudoers
        line: '%{{ domain_name.split(".")[0] }}\\domain^admins ALL=(ALL:ALL) ALL'
        validate: 'visudo -cf %s'
