---
- name: Check and Disable SELinux on Oracle Servers
  hosts: linux
  become: yes
  tasks:
    - name: Check if SELinux is enabled
      command: getenforce
      register: selinux_status

    - name: Debug SELinux status
      debug:
        msg: "SELinux status is {{ selinux_status.stdout }}"

    - name: Disable SELinux if enabled
      when: selinux_status.stdout != "Disabled"
      block:
        - name: Set SELinux to permissive mode temporarily
          command: setenforce 0

        - name: Disable SELinux permanently in config file
          replace:
            path: /etc/selinux/config
            regexp: '^SELINUX=enforcing'
            replace: 'SELINUX=disabled'
            backup: yes
