---
- name: Output Ansible version in SQL format
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  gather_facts: false
  tasks:
    - name: Ansible version
      command: ansible --version
      register: ansible_version_output

    - name: Create SQL table format output
      set_fact:
        sql_output: |
          CREATE TABLE ansible_version_details (
              id INTEGER PRIMARY KEY,
              description TEXT,
              value TEXT
          );

          {% for line in ansible_version_output.stdout_lines %}
          INSERT INTO ansible_version_details (id, description, value) VALUES
          ({{ loop.index }}, '{{ line.split('=')[0].strip() if '=' in line else line.split()[0] }}', '{{ line.split('=')[1].strip() if '=' in line else line.split(maxsplit=1)[1] }}');
          {% endfor %}

    - name: Display SQL table format output
      debug:
        msg: "{{ sql_output }}"
...
