---
- name: Output Ansible version
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Get Ansible version
      command: ansible --version
      register: ansible_version_output

    - name: Print Ansible version
      debug:
        msg: "{{ ansible_version_output.stdout }}"
