---
- name: Output Ansible version in table format
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  gather_facts: false
  tasks:
    - name: Get Ansible version details
      command: ansible --version
      register: ansible_version_output

    - name: Create table format output
      set_fact:
        table_output: |
          +----------------------------------+-----------------------------------------------------------------------+
          | Description                      | Value                                                                 |
          +----------------------------------+-----------------------------------------------------------------------+
          {% for line in ansible_version_output.stdout_lines %}
          {% if '=' in line %}
          | {{ '{:<32}'.format(line.split('=')[0].strip()) }} | {{ '{:<63}'.format(line.split('=')[1].strip()) }} |
          {% else %}
          | {{ '{:<32}'.format(line.split(maxsplit=1)[0].strip()) }} | {{ '{:<63}'.format(line.split(maxsplit=1)[1].strip()) }} |
          {% endif %}
          +----------------------------------+-----------------------------------------------------------------------+
          {% endfor %}

    - name: Display table format output
      debug:
        msg: "{{ table_output }}"
...
