---
- name: Output Ansible version in table format
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Get Ansible version details
      command: ansible --version
      register: ansible_version_output

    - name: Parse version details into a table format
      set_fact:
        table_output: |
          +----------------------------------+-----------------------------------------------------------------------+
          | Description                      | Value                                                                 |
          +----------------------------------+-----------------------------------------------------------------------+
          {% for line in ansible_version_output.stdout_lines %}
          | {{ line.split(":")[0]|default("").strip()|truncate(32, True, '…') }} | {{ line.split(":")[1]|default("").strip()|truncate(63, True, '…') }} |
          +----------------------------------+-----------------------------------------------------------------------+
          {% endfor %}

    - name: Display table format output
      debug:
        msg: "{{ table_output }}"
...
