---
- name: Output Ansible version
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  gather_facts: false
  tasks:
    - name: Ansible version
      command: ansible --version
      register: ansible_version_output

    - name: Parse Ansible version details
      set_fact:
        ansible_version_details: |
          {%- set details = {} -%}
          {%- for line in ansible_version_output.stdout_lines[1:] %}
            {%- set key_value = line.strip().split('=', 1) %}
            {%- if key_value | length == 2 %}
              {%- set _ = details.update({ key_value[0].strip(): key_value[1].strip() }) %}
            {%- else %}
              {%- set _ = details.update({ 'ansible_version': key_value[0].strip() }) %}
            {%- endif %}
          {%- endfor %}
          {{ details }}

    - name: Print Ansible version details in table format
      debug:
        msg: |
          | Key                                | Value                                                                 |
          |------------------------------------|-----------------------------------------------------------------------|
          {% for key, value in ansible_version_details.items() %}
          | {{ key.ljust(34) }} | {{ value }} |
          {% endfor %}
...
