---
- name: Output Ansible version in table format
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Get Ansible version details
      command: ansible --version
      register: ansible_version_output

    - name: Parse version details
      set_fact:
        parsed_lines: >
          {%- set result = [] -%}
          {%- for line in ansible_version_output.stdout_lines %}
            {%- if '=' in line %}
              {%- set parts = line.split('=', 1) -%}
              {%- set result = result + [{'desc': parts[0].strip(), 'value': parts[1].strip()}] -%}
            {%- else %}
              {%- set parts = line.split(maxsplit=1) -%}
              {%- if parts|length == 2 -%}
                {%- set result = result + [{'desc': parts[0].strip(), 'value': parts[1].strip()}] -%}
              {%- endif -%}
            {%- endif %}
          {%- endfor -%}
          {{ result }}

    - name: Create table format output
      set_fact:
        table_output: >
          +----------------------------------+-----------------------------------------------------------------------+
          | Description                      | Value                                                                 |
          +----------------------------------+-----------------------------------------------------------------------+
          {% for item in parsed_lines %}
          | {{ '{:<32}'.format(item.desc) }} | {{ '{:<63}'.format(item.value) }} |
          +----------------------------------+-----------------------------------------------------------------------+
          {% endfor %}

    - name: Display table format output
      debug:
        msg: |
          {{ table_output }}
...
