---
- name: Output Ansible version
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  gather_facts: false
  tasks:
    - name: Ansible version
      command: ansible --version
      register: ansible_version_output

    - name: Print Ansible version details
      debug:
        msg: "{{ item }}"
      loop: "{{ ansible_version_output.stdout_lines }}"
...
