---
- name: Upgrade Packages on localhost
  hosts: localhost
  become: yes
  connection: local

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade all packages to the latest version
      ansible.builtin.apt:
        upgrade: dist
      register: upgrade_output

    - name: Output upgraded packages
      debug:
        msg: "{{ upgrade_output.stdout_lines }}"
      when: upgrade_output.changed
...
