---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Get list of installed collections
      command: ansible-galaxy collection list
      register: collections_output

    - name: Parse collections output
      set_fact:
        collections: "{{ collections_output.stdout_lines[2:] | map('regex_replace', '^(\\S+)\\s+(\\S+)\\s+.*$', '\\1.\\2') | list }}"

    - name: Reinstall all collections
      command: ansible-galaxy collection install -f "{{ item }}"
      loop: "{{ collections }}"
