---
- name: Update Arch Linux system packages
  hosts: all
  become: true
  tasks:

    - name: Force refresh the package database
      ansible.builtin.command: pacman -Syy --noconfirm
      register: refresh_output
      changed_when: "'downloading' in refresh_output.stdout"

    - name: Upgrade all packages
      ansible.builtin.command: pacman -Su --noconfirm
      register: upgrade_output
      changed_when: "'Packages' in upgrade_output.stdout"
...
